# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bunary.proto\x12\x05unary\"\x18\n\x07Request\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1b\n\x08Repspone\x12\x0f\n\x07message\x18\x01 \x01(\t25\n\x07Greeter\x12*\n\x05\x45mail\x12\x0e.unary.Request\x1a\x0f.unary.Repspone\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unary_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=22
  _REQUEST._serialized_end=46
  _REPSPONE._serialized_start=48
  _REPSPONE._serialized_end=75
  _GREETER._serialized_start=77
  _GREETER._serialized_end=130
# @@protoc_insertion_point(module_scope)
